### ISSUE TITLE
3 little defects

### ISSUE THREAD

**Issue by zcyzcy88** [Lootyhoof/maxi4#1]
1. when tabs are overflow, the tab bar height will change from 29px to 28px
2. when window maximize, "new tab page" button are a little under from top, are not easy to click
3. tabs are too short (60px)

Here is my workaround:
```css
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");

.box-inherit.scrollbox-innerbox {
	height: 29px !important;
}
.tabs-newtab-button {
	height: 28px !important;
	margin-top: 0px !important;
	margin-bottom: 0px !important;
}
.tabbrowser-tab[fadein]:not([pinned]) {
	min-width: 120px !important;
}
```
